# Generated by Django 5.1.4 on 2025-01-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('payment', models.IntegerField(verbose_name='Ежемесячная оплата')),
                ('number_of_rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('size_of_apartment', models.FloatField(verbose_name='Квадратуры квартиры')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('furniture', models.CharField(blank=True, max_length=255, verbose_name='Мебель')),
                ('technique', models.CharField(blank=True, max_length=255, verbose_name='Техника')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='rent_house.category', verbose_name='Категории')),
            ],
        ),
    ]
