# Generated by Django 5.1.4 on 2025-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_house', '0002_appartments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartments',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
